// Code generated by go-swagger; DO NOT EDIT.

package object_upload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/node-real/greenfield-bundle-service/models"
)

// UploadObjectsOKCode is the HTTP code returned for type UploadObjectsOK
const UploadObjectsOKCode int = 200

/*
UploadObjectsOK Successfully uploaded file

swagger:response uploadObjectsOK
*/
type UploadObjectsOK struct {

	/*
	  In: Body
	*/
	Payload *UploadObjectsOKBody `json:"body,omitempty"`
}

// NewUploadObjectsOK creates UploadObjectsOK with default headers values
func NewUploadObjectsOK() *UploadObjectsOK {

	return &UploadObjectsOK{}
}

// WithPayload adds the payload to the upload objects o k response
func (o *UploadObjectsOK) WithPayload(payload *UploadObjectsOKBody) *UploadObjectsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload objects o k response
func (o *UploadObjectsOK) SetPayload(payload *UploadObjectsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadObjectsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UploadObjectsBadRequestCode is the HTTP code returned for type UploadObjectsBadRequest
const UploadObjectsBadRequestCode int = 400

/*
UploadObjectsBadRequest Invalid request or file format

swagger:response uploadObjectsBadRequest
*/
type UploadObjectsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUploadObjectsBadRequest creates UploadObjectsBadRequest with default headers values
func NewUploadObjectsBadRequest() *UploadObjectsBadRequest {

	return &UploadObjectsBadRequest{}
}

// WithPayload adds the payload to the upload objects bad request response
func (o *UploadObjectsBadRequest) WithPayload(payload *models.Error) *UploadObjectsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload objects bad request response
func (o *UploadObjectsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadObjectsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UploadObjectsInternalServerErrorCode is the HTTP code returned for type UploadObjectsInternalServerError
const UploadObjectsInternalServerErrorCode int = 500

/*
UploadObjectsInternalServerError Internal server error

swagger:response uploadObjectsInternalServerError
*/
type UploadObjectsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUploadObjectsInternalServerError creates UploadObjectsInternalServerError with default headers values
func NewUploadObjectsInternalServerError() *UploadObjectsInternalServerError {

	return &UploadObjectsInternalServerError{}
}

// WithPayload adds the payload to the upload objects internal server error response
func (o *UploadObjectsInternalServerError) WithPayload(payload *models.Error) *UploadObjectsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload objects internal server error response
func (o *UploadObjectsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadObjectsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
