// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/node-real/greenfield-bundle-service/restapi/operations/bundle"
	"github.com/node-real/greenfield-bundle-service/restapi/operations/rule"
)

// NewBundleServiceAPI creates a new BundleService instance
func NewBundleServiceAPI(spec *loads.Document) *BundleServiceAPI {
	return &BundleServiceAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer:          runtime.JSONConsumer(),
		MultipartformConsumer: runtime.DiscardConsumer,

		BinProducer:  runtime.ByteStreamProducer(),
		JSONProducer: runtime.JSONProducer(),

		BundleBundlerAccountHandler: bundle.BundlerAccountHandlerFunc(func(params bundle.BundlerAccountParams) middleware.Responder {
			return middleware.NotImplemented("operation bundle.BundlerAccount has not yet been implemented")
		}),
		BundleCreateBundleHandler: bundle.CreateBundleHandlerFunc(func(params bundle.CreateBundleParams) middleware.Responder {
			return middleware.NotImplemented("operation bundle.CreateBundle has not yet been implemented")
		}),
		BundleDeleteBundleHandler: bundle.DeleteBundleHandlerFunc(func(params bundle.DeleteBundleParams) middleware.Responder {
			return middleware.NotImplemented("operation bundle.DeleteBundle has not yet been implemented")
		}),
		BundleDownloadBundleObjectHandler: bundle.DownloadBundleObjectHandlerFunc(func(params bundle.DownloadBundleObjectParams) middleware.Responder {
			return middleware.NotImplemented("operation bundle.DownloadBundleObject has not yet been implemented")
		}),
		BundleFinalizeBundleHandler: bundle.FinalizeBundleHandlerFunc(func(params bundle.FinalizeBundleParams) middleware.Responder {
			return middleware.NotImplemented("operation bundle.FinalizeBundle has not yet been implemented")
		}),
		BundleQueryBundleHandler: bundle.QueryBundleHandlerFunc(func(params bundle.QueryBundleParams) middleware.Responder {
			return middleware.NotImplemented("operation bundle.QueryBundle has not yet been implemented")
		}),
		BundleQueryBundlingBundleHandler: bundle.QueryBundlingBundleHandlerFunc(func(params bundle.QueryBundlingBundleParams) middleware.Responder {
			return middleware.NotImplemented("operation bundle.QueryBundlingBundle has not yet been implemented")
		}),
		RuleSetBundleRuleHandler: rule.SetBundleRuleHandlerFunc(func(params rule.SetBundleRuleParams) middleware.Responder {
			return middleware.NotImplemented("operation rule.SetBundleRule has not yet been implemented")
		}),
		BundleUploadBundleHandler: bundle.UploadBundleHandlerFunc(func(params bundle.UploadBundleParams) middleware.Responder {
			return middleware.NotImplemented("operation bundle.UploadBundle has not yet been implemented")
		}),
		BundleUploadObjectHandler: bundle.UploadObjectHandlerFunc(func(params bundle.UploadObjectParams) middleware.Responder {
			return middleware.NotImplemented("operation bundle.UploadObject has not yet been implemented")
		}),
		BundleViewBundleObjectHandler: bundle.ViewBundleObjectHandlerFunc(func(params bundle.ViewBundleObjectParams) middleware.Responder {
			return middleware.NotImplemented("operation bundle.ViewBundleObject has not yet been implemented")
		}),
	}
}

/*BundleServiceAPI API for handling file bundling and querying objects in the Bundle Service. */
type BundleServiceAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer
	// MultipartformConsumer registers a consumer for the following mime types:
	//   - multipart/form-data
	MultipartformConsumer runtime.Consumer

	// BinProducer registers a producer for the following mime types:
	//   - application/octet-stream
	BinProducer runtime.Producer
	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BundleBundlerAccountHandler sets the operation handler for the bundler account operation
	BundleBundlerAccountHandler bundle.BundlerAccountHandler
	// BundleCreateBundleHandler sets the operation handler for the create bundle operation
	BundleCreateBundleHandler bundle.CreateBundleHandler
	// BundleDeleteBundleHandler sets the operation handler for the delete bundle operation
	BundleDeleteBundleHandler bundle.DeleteBundleHandler
	// BundleDownloadBundleObjectHandler sets the operation handler for the download bundle object operation
	BundleDownloadBundleObjectHandler bundle.DownloadBundleObjectHandler
	// BundleFinalizeBundleHandler sets the operation handler for the finalize bundle operation
	BundleFinalizeBundleHandler bundle.FinalizeBundleHandler
	// BundleQueryBundleHandler sets the operation handler for the query bundle operation
	BundleQueryBundleHandler bundle.QueryBundleHandler
	// BundleQueryBundlingBundleHandler sets the operation handler for the query bundling bundle operation
	BundleQueryBundlingBundleHandler bundle.QueryBundlingBundleHandler
	// RuleSetBundleRuleHandler sets the operation handler for the set bundle rule operation
	RuleSetBundleRuleHandler rule.SetBundleRuleHandler
	// BundleUploadBundleHandler sets the operation handler for the upload bundle operation
	BundleUploadBundleHandler bundle.UploadBundleHandler
	// BundleUploadObjectHandler sets the operation handler for the upload object operation
	BundleUploadObjectHandler bundle.UploadObjectHandler
	// BundleViewBundleObjectHandler sets the operation handler for the view bundle object operation
	BundleViewBundleObjectHandler bundle.ViewBundleObjectHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *BundleServiceAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *BundleServiceAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *BundleServiceAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *BundleServiceAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *BundleServiceAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *BundleServiceAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *BundleServiceAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *BundleServiceAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *BundleServiceAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the BundleServiceAPI
func (o *BundleServiceAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}
	if o.MultipartformConsumer == nil {
		unregistered = append(unregistered, "MultipartformConsumer")
	}

	if o.BinProducer == nil {
		unregistered = append(unregistered, "BinProducer")
	}
	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BundleBundlerAccountHandler == nil {
		unregistered = append(unregistered, "bundle.BundlerAccountHandler")
	}
	if o.BundleCreateBundleHandler == nil {
		unregistered = append(unregistered, "bundle.CreateBundleHandler")
	}
	if o.BundleDeleteBundleHandler == nil {
		unregistered = append(unregistered, "bundle.DeleteBundleHandler")
	}
	if o.BundleDownloadBundleObjectHandler == nil {
		unregistered = append(unregistered, "bundle.DownloadBundleObjectHandler")
	}
	if o.BundleFinalizeBundleHandler == nil {
		unregistered = append(unregistered, "bundle.FinalizeBundleHandler")
	}
	if o.BundleQueryBundleHandler == nil {
		unregistered = append(unregistered, "bundle.QueryBundleHandler")
	}
	if o.BundleQueryBundlingBundleHandler == nil {
		unregistered = append(unregistered, "bundle.QueryBundlingBundleHandler")
	}
	if o.RuleSetBundleRuleHandler == nil {
		unregistered = append(unregistered, "rule.SetBundleRuleHandler")
	}
	if o.BundleUploadBundleHandler == nil {
		unregistered = append(unregistered, "bundle.UploadBundleHandler")
	}
	if o.BundleUploadObjectHandler == nil {
		unregistered = append(unregistered, "bundle.UploadObjectHandler")
	}
	if o.BundleViewBundleObjectHandler == nil {
		unregistered = append(unregistered, "bundle.ViewBundleObjectHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *BundleServiceAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *BundleServiceAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *BundleServiceAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *BundleServiceAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		case "multipart/form-data":
			result["multipart/form-data"] = o.MultipartformConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *BundleServiceAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/octet-stream":
			result["application/octet-stream"] = o.BinProducer
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *BundleServiceAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the bundle service API
func (o *BundleServiceAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *BundleServiceAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/bundlerAccount/{userAddress}"] = bundle.NewBundlerAccount(o.context, o.BundleBundlerAccountHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/createBundle"] = bundle.NewCreateBundle(o.context, o.BundleCreateBundleHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/deleteBundle"] = bundle.NewDeleteBundle(o.context, o.BundleDeleteBundleHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/download/{bucketName}/{bundleName}/{objectName}"] = bundle.NewDownloadBundleObject(o.context, o.BundleDownloadBundleObjectHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/finalizeBundle"] = bundle.NewFinalizeBundle(o.context, o.BundleFinalizeBundleHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/queryBundle/{bucketName}/{bundleName}"] = bundle.NewQueryBundle(o.context, o.BundleQueryBundleHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/queryBundlingBundle/{bucketName}"] = bundle.NewQueryBundlingBundle(o.context, o.BundleQueryBundlingBundleHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/setBundleRule"] = rule.NewSetBundleRule(o.context, o.RuleSetBundleRuleHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/uploadBundle"] = bundle.NewUploadBundle(o.context, o.BundleUploadBundleHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/uploadObject"] = bundle.NewUploadObject(o.context, o.BundleUploadObjectHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/view/{bucketName}/{bundleName}/{objectName}"] = bundle.NewViewBundleObject(o.context, o.BundleViewBundleObjectHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *BundleServiceAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *BundleServiceAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *BundleServiceAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *BundleServiceAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *BundleServiceAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
