// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Bundle Service API
//
//	API for handling file bundling and querying objects in the Bundle Service.
//	Schemes:
//	  https
//	Host: bundle-service.nodereal.io
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - multipart/form-data
//
//	Produces:
//	  - application/octet-stream
//
// swagger:meta
package restapi
