// Code generated by go-swagger; DO NOT EDIT.

package bundle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// BundlerAccountHandlerFunc turns a function with the right signature into a bundler account handler
type BundlerAccountHandlerFunc func(BundlerAccountParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BundlerAccountHandlerFunc) Handle(params BundlerAccountParams) middleware.Responder {
	return fn(params)
}

// BundlerAccountHandler interface for that can handle valid bundler account params
type BundlerAccountHandler interface {
	Handle(BundlerAccountParams) middleware.Responder
}

// NewBundlerAccount creates a new http.Handler for the bundler account operation
func NewBundlerAccount(ctx *middleware.Context, handler BundlerAccountHandler) *BundlerAccount {
	return &BundlerAccount{Context: ctx, Handler: handler}
}

/*
	BundlerAccount swagger:route POST /bundlerAccount/{userAddress} Bundle bundlerAccount

# Get Bundler Account for a User

Returns the bundler account for a given user.
*/
type BundlerAccount struct {
	Context *middleware.Context
	Handler BundlerAccountHandler
}

func (o *BundlerAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewBundlerAccountParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
