// Code generated by go-swagger; DO NOT EDIT.

package bundle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateBundleHandlerFunc turns a function with the right signature into a create bundle handler
type CreateBundleHandlerFunc func(CreateBundleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateBundleHandlerFunc) Handle(params CreateBundleParams) middleware.Responder {
	return fn(params)
}

// CreateBundleHandler interface for that can handle valid create bundle params
type CreateBundleHandler interface {
	Handle(CreateBundleParams) middleware.Responder
}

// NewCreateBundle creates a new http.Handler for the create bundle operation
func NewCreateBundle(ctx *middleware.Context, handler CreateBundleHandler) *CreateBundle {
	return &CreateBundle{Context: ctx, Handler: handler}
}

/*
	CreateBundle swagger:route POST /createBundle Bundle createBundle

# Start a New Bundle

Initiates a new bundle, requiring details like bucket name and bundle name.
*/
type CreateBundle struct {
	Context *middleware.Context
	Handler CreateBundleHandler
}

func (o *CreateBundle) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateBundleParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
