// Code generated by go-swagger; DO NOT EDIT.

package bundle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/node-real/greenfield-bundle-service/models"
)

// DownloadBundleObjectOKCode is the HTTP code returned for type DownloadBundleObjectOK
const DownloadBundleObjectOKCode int = 200

/*
DownloadBundleObjectOK Successfully retrieved file

swagger:response downloadBundleObjectOK
*/
type DownloadBundleObjectOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewDownloadBundleObjectOK creates DownloadBundleObjectOK with default headers values
func NewDownloadBundleObjectOK() *DownloadBundleObjectOK {

	return &DownloadBundleObjectOK{}
}

// WithPayload adds the payload to the download bundle object o k response
func (o *DownloadBundleObjectOK) WithPayload(payload io.ReadCloser) *DownloadBundleObjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download bundle object o k response
func (o *DownloadBundleObjectOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadBundleObjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DownloadBundleObjectBadRequestCode is the HTTP code returned for type DownloadBundleObjectBadRequest
const DownloadBundleObjectBadRequestCode int = 400

/*
DownloadBundleObjectBadRequest Invalid request or file format

swagger:response downloadBundleObjectBadRequest
*/
type DownloadBundleObjectBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDownloadBundleObjectBadRequest creates DownloadBundleObjectBadRequest with default headers values
func NewDownloadBundleObjectBadRequest() *DownloadBundleObjectBadRequest {

	return &DownloadBundleObjectBadRequest{}
}

// WithPayload adds the payload to the download bundle object bad request response
func (o *DownloadBundleObjectBadRequest) WithPayload(payload *models.Error) *DownloadBundleObjectBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download bundle object bad request response
func (o *DownloadBundleObjectBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadBundleObjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadBundleObjectNotFoundCode is the HTTP code returned for type DownloadBundleObjectNotFound
const DownloadBundleObjectNotFoundCode int = 404

/*
DownloadBundleObjectNotFound Bundle or object not found

swagger:response downloadBundleObjectNotFound
*/
type DownloadBundleObjectNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDownloadBundleObjectNotFound creates DownloadBundleObjectNotFound with default headers values
func NewDownloadBundleObjectNotFound() *DownloadBundleObjectNotFound {

	return &DownloadBundleObjectNotFound{}
}

// WithPayload adds the payload to the download bundle object not found response
func (o *DownloadBundleObjectNotFound) WithPayload(payload *models.Error) *DownloadBundleObjectNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download bundle object not found response
func (o *DownloadBundleObjectNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadBundleObjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadBundleObjectInternalServerErrorCode is the HTTP code returned for type DownloadBundleObjectInternalServerError
const DownloadBundleObjectInternalServerErrorCode int = 500

/*
DownloadBundleObjectInternalServerError Internal server error

swagger:response downloadBundleObjectInternalServerError
*/
type DownloadBundleObjectInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDownloadBundleObjectInternalServerError creates DownloadBundleObjectInternalServerError with default headers values
func NewDownloadBundleObjectInternalServerError() *DownloadBundleObjectInternalServerError {

	return &DownloadBundleObjectInternalServerError{}
}

// WithPayload adds the payload to the download bundle object internal server error response
func (o *DownloadBundleObjectInternalServerError) WithPayload(payload *models.Error) *DownloadBundleObjectInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download bundle object internal server error response
func (o *DownloadBundleObjectInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadBundleObjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
