// Code generated by go-swagger; DO NOT EDIT.

package bundle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FinalizeBundleHandlerFunc turns a function with the right signature into a finalize bundle handler
type FinalizeBundleHandlerFunc func(FinalizeBundleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FinalizeBundleHandlerFunc) Handle(params FinalizeBundleParams) middleware.Responder {
	return fn(params)
}

// FinalizeBundleHandler interface for that can handle valid finalize bundle params
type FinalizeBundleHandler interface {
	Handle(FinalizeBundleParams) middleware.Responder
}

// NewFinalizeBundle creates a new http.Handler for the finalize bundle operation
func NewFinalizeBundle(ctx *middleware.Context, handler FinalizeBundleHandler) *FinalizeBundle {
	return &FinalizeBundle{Context: ctx, Handler: handler}
}

/*
	FinalizeBundle swagger:route POST /finalizeBundle Bundle finalizeBundle

# Finalize an Existing Bundle

Completes the lifecycle of an existing bundle, requiring the bundle name for authorization.
*/
type FinalizeBundle struct {
	Context *middleware.Context
	Handler FinalizeBundleHandler
}

func (o *FinalizeBundle) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFinalizeBundleParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
