// Code generated by go-swagger; DO NOT EDIT.

package bundle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UploadObjectHandlerFunc turns a function with the right signature into a upload object handler
type UploadObjectHandlerFunc func(UploadObjectParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadObjectHandlerFunc) Handle(params UploadObjectParams) middleware.Responder {
	return fn(params)
}

// UploadObjectHandler interface for that can handle valid upload object params
type UploadObjectHandler interface {
	Handle(UploadObjectParams) middleware.Responder
}

// NewUploadObject creates a new http.Handler for the upload object operation
func NewUploadObject(ctx *middleware.Context, handler UploadObjectHandler) *UploadObject {
	return &UploadObject{Context: ctx, Handler: handler}
}

/*
	UploadObject swagger:route POST /uploadObject Bundle uploadObject

# Upload a single object to a bundle

Allows users to upload a single file along with a signature for validation, and a timestamp.
*/
type UploadObject struct {
	Context *middleware.Context
	Handler UploadObjectHandler
}

func (o *UploadObject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUploadObjectParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// UploadObjectOKBody upload object o k body
//
// swagger:model UploadObjectOKBody
type UploadObjectOKBody struct {

	// The name of the bundle where the file has been uploaded
	BundleName string `json:"bundleName,omitempty"`
}

// Validate validates this upload object o k body
func (o *UploadObjectOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this upload object o k body based on context it is used
func (o *UploadObjectOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UploadObjectOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UploadObjectOKBody) UnmarshalBinary(b []byte) error {
	var res UploadObjectOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
