// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QueryObjectResponse query object response
//
// swagger:model QueryObjectResponse
type QueryObjectResponse struct {

	// The name of the bucket where the file has been uploaded
	BucketName string `json:"bucketName,omitempty"`

	// The name of the bundle where the file has been uploaded
	BundleName string `json:"bundleName,omitempty"`

	// The name of the object within the bundle
	ObjectName string `json:"objectName,omitempty"`

	// The status of the object
	Status string `json:"status,omitempty"`
}

// Validate validates this query object response
func (m *QueryObjectResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query object response based on context it is used
func (m *QueryObjectResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QueryObjectResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryObjectResponse) UnmarshalBinary(b []byte) error {
	var res QueryObjectResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
